### ISSUE TITLE
LOD project link doesn't work

### ISSUE THREAD

**Issue by ross-spencer** [Smithsonian/lod-pilot#1]
The following link https://si-confluence.si.edu/display/LOD on the project main page is not resolving. The CURL response is as follows:
```
*   Trying 62.138.239.45...
* TCP_NODELAY set
* connect to 62.138.239.45 port 443 failed: Connection refused
*   Trying 62.138.238.45...
* TCP_NODELAY set
* connect to 62.138.238.45 port 443 failed: Connection refused
* Failed to connect to si-confluence.si.edu port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to si-confluence.si.edu port 443: Connection refused
```

**Comment by ajs6f** [comment]
That's as should be. The planning site for this repo isn't currently public. This repo will be used mostly for technical collaboration. I will certainly look into making at least some part of the planning site public. (And perhaps getting a more helpful response to unauthorized traffic on that Confluence site.)

**Comment by ajs6f** [comment]
@ross-spencer We will start working on a public site with good info-- it will probably not appear for a few weeks (pressure of work) but soon! Ish!
